export const appointment = [
	{
		id: 'EV-001',
		patientId: 'PB-001',
		doctor: 'Dr. Olivia Grant',
		title: 'Facial Rejuvenation',
		start: '09:00 AM',
		end: '10:00 AM',
		room: 'OR 1',
		date: '2028-09-12',
		status: 'Completed',
		color: 'bg-rose-100 border border-rose-300',
		notes: 'Patient responded well to treatment. No side effects reported.'
	},
	{
		id: 'EV-002',
		patientId: 'PB-002',
		doctor: 'Dr. David Carter',
		title: 'Laser Hair Removal',
		start: '12:00 PM',
		end: '01:00 PM',
		room: 'OR 3',
		date: '2028-09-12',
		status: 'In Progress',
		color: 'bg-blue-100 border border-blue-300',
		notes: 'Session ongoing. Mild redness observed.'
	},
	{
		id: 'EV-003',
		patientId: 'PB-003',
		doctor: 'Dr. Emily Ross',
		title: 'Botox Injections',
		start: '02:30 PM',
		end: '03:30 PM',
		room: 'OR 2',
		date: '2028-09-12',
		status: 'Scheduled',
		color: 'bg-green-100 border border-green-300',
		notes: 'Patient advised to avoid alcohol 24 hours before treatment.'
	},
	{
		id: 'EV-004',
		patientId: 'PB-004',
		doctor: 'Dr. James Lawson',
		title: 'Microdermabrasion',
		start: '04:30 PM',
		end: '05:30 PM',
		room: 'OR 1',
		date: '2028-09-12',
		status: 'Completed',
		color: 'bg-purple-100 border border-purple-300',
		notes: 'Skin improvement visible. Follow-up scheduled in 3 weeks.'
	},
	{
		id: 'EV-005',
		patientId: 'PB-005',
		doctor: 'Dr. Sophia Clark',
		title: 'Chemical Peels',
		start: '09:30 AM',
		end: '10:30 AM',
		room: 'OR 3',
		date: '2028-09-13',
		status: 'In Progress',
		color: 'bg-pink-100 border border-pink-300',
		notes: 'Peeling process started. Patient experiencing mild tingling.'
	},
	{
		id: 'EV-006',
		patientId: 'PB-006',
		doctor: 'Dr. Richard Allen',
		title: 'Body Contouring',
		start: '01:00 PM',
		end: '02:00 PM',
		room: 'OR 4',
		date: '2028-09-13',
		status: 'Scheduled',
		color: 'bg-yellow-100 border border-yellow-300',
		notes: 'Patient instructed to fast 6 hours prior to procedure.'
	},
	{
		id: 'EV-007',
		patientId: 'PB-007',
		doctor: 'Dr. Megan Foster',
		title: 'Acne Treatment',
		start: '04:00 PM',
		end: '05:00 PM',
		room: 'OR 2',
		date: '2028-09-13',
		status: 'Completed',
		color: 'bg-emerald-100 border border-emerald-300',
		notes: 'Treatment successful. Prescribed topical cream for maintenance.'
	},
	{
		id: 'EV-008',
		patientId: 'PB-008',
		doctor: 'Dr. David Carter',
		title: 'Laser Hair Removal',
		start: '12:00 PM',
		end: '01:00 PM',
		room: 'OR 3',
		date: '2028-09-12',
		status: 'Cancelled',
		color: 'bg-gray-200 border border-gray-300',
		notes: 'Appointment cancelled due to patient illness.'
	},
	{
		id: 'EV-009',
		patientId: 'PB-009',
		doctor: 'Dr. James Lawson',
		title: 'Microdermabrasion',
		start: '04:30 PM',
		end: '05:30 PM',
		room: 'OR 1',
		date: '2028-09-12',
		status: 'Completed',
		color: 'bg-indigo-100 border border-indigo-300',
		notes: 'Post-treatment care instructions provided.'
	},
	{
		id: 'EV-010',
		patientId: 'PB-010',
		doctor: 'Dr. Richard Allen',
		title: 'Body Contouring',
		start: '01:00 PM',
		end: '02:00 PM',
		room: 'OR 4',
		date: '2028-09-13',
		status: 'Scheduled',
		color: 'bg-orange-100 border border-orange-300',
		notes: 'Patient to bring previous medical reports for evaluation.'
	},
	{
		id: 'EV-011',
		patientId: 'PB-010',
		doctor: 'Dr. Richard Allen',
		title: 'Microdermabrasion',
		start: '03:00 PM',
		end: '04:00 PM',
		room: 'OR 4',
		date: '2028-10-19',
		status: 'Completed',
		color: 'bg-orange-100 border border-orange-300',
		notes: 'Patient to bring previous medical reports for evaluation.'
	}
];
