"""change the data type of note column in medical info table

Revision ID: 4e7dbcaeaafe
Revises: 0d15c7ebe490
Create Date: 2025-08-28 11:22:49.372208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7dbcaeaafe'
down_revision: Union[str, Sequence[str], None] = '0d15c7ebe490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_doctorId_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_patientId_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_treatmentId_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'treatments', ['treatmentId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctorId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'patients', ['patientId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('doctor_availability_doctorId_fkey'), 'doctor_availability', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_availability', 'doctors', ['doctorId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('doctor_treatment_junction_doctorId_fkey'), 'doctor_treatment_junction', type_='foreignkey')
    op.drop_constraint(op.f('doctor_treatment_junction_treatmentId_fkey'), 'doctor_treatment_junction', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_treatment_junction', 'treatments', ['treatmentId'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'doctor_treatment_junction', 'doctors', ['doctorId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('health_reports_patient_id_fkey'), 'health_reports', type_='foreignkey')
    op.drop_constraint(op.f('health_reports_doctor_id_fkey'), 'health_reports', type_='foreignkey')
    op.create_foreign_key(None, 'health_reports', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'health_reports', 'patients', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('medications_doctor_id_fkey'), 'medications', type_='foreignkey')
    op.drop_constraint(op.f('medications_patient_id_fkey'), 'medications', type_='foreignkey')
    op.create_foreign_key(None, 'medications', 'patients', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'medications', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('patient_files_patientId_fkey'), 'patient_files', type_='foreignkey')
    op.create_foreign_key(None, 'patient_files', 'patients', ['patientId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('patient_medical_info_appointmentId_fkey'), 'patient_medical_info', type_='foreignkey')
    op.drop_constraint(op.f('patient_medical_info_patientId_fkey'), 'patient_medical_info', type_='foreignkey')
    op.create_foreign_key(None, 'patient_medical_info', 'appointments', ['appointmentId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'patient_medical_info', 'patients', ['patientId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('reviews_patient_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_doctor_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_treatment_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'treatments', ['treatment_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'reviews', 'patients', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'reviews', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('role_permission_junction_roleId_fkey'), 'role_permission_junction', type_='foreignkey')
    op.drop_constraint(op.f('role_permission_junction_permissionId_fkey'), 'role_permission_junction', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission_junction', 'permissions', ['permissionId'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'role_permission_junction', 'roles', ['roleId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('surgeries_performed_doctor_id_fkey'), 'surgeries_performed', type_='foreignkey')
    op.drop_constraint(op.f('surgeries_performed_patient_id_fkey'), 'surgeries_performed', type_='foreignkey')
    op.create_foreign_key(None, 'surgeries_performed', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'surgeries_performed', 'patients', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('surgery_schedules_doctor_id_fkey'), 'surgery_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'surgery_schedules', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('users_roleId_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['roleId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('users_roleId_fkey'), 'users', 'roles', ['roleId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'surgery_schedules', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('surgery_schedules_doctor_id_fkey'), 'surgery_schedules', 'doctors', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'surgeries_performed', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'surgeries_performed', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('surgeries_performed_patient_id_fkey'), 'surgeries_performed', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('surgeries_performed_doctor_id_fkey'), 'surgeries_performed', 'doctors', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'role_permission_junction', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'role_permission_junction', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('role_permission_junction_permissionId_fkey'), 'role_permission_junction', 'permissions', ['permissionId'], ['id'])
    op.create_foreign_key(op.f('role_permission_junction_roleId_fkey'), 'role_permission_junction', 'roles', ['roleId'], ['id'])
    op.drop_constraint(None, 'reviews', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'reviews', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'reviews', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_treatment_id_fkey'), 'reviews', 'treatments', ['treatment_id'], ['id'])
    op.create_foreign_key(op.f('reviews_doctor_id_fkey'), 'reviews', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key(op.f('reviews_patient_id_fkey'), 'reviews', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'patient_medical_info', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'patient_medical_info', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('patient_medical_info_patientId_fkey'), 'patient_medical_info', 'patients', ['patientId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('patient_medical_info_appointmentId_fkey'), 'patient_medical_info', 'appointments', ['appointmentId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'patient_files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('patient_files_patientId_fkey'), 'patient_files', 'patients', ['patientId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'medications', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'medications', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('medications_patient_id_fkey'), 'medications', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('medications_doctor_id_fkey'), 'medications', 'doctors', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'health_reports', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'health_reports', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('health_reports_doctor_id_fkey'), 'health_reports', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key(op.f('health_reports_patient_id_fkey'), 'health_reports', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'doctor_treatment_junction', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'doctor_treatment_junction', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_treatment_junction_treatmentId_fkey'), 'doctor_treatment_junction', 'treatments', ['treatmentId'], ['id'])
    op.create_foreign_key(op.f('doctor_treatment_junction_doctorId_fkey'), 'doctor_treatment_junction', 'doctors', ['doctorId'], ['id'])
    op.drop_constraint(None, 'doctor_availability', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_availability_doctorId_fkey'), 'doctor_availability', 'doctors', ['doctorId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_treatmentId_fkey'), 'appointments', 'treatments', ['treatmentId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('appointments_patientId_fkey'), 'appointments', 'patients', ['patientId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('appointments_doctorId_fkey'), 'appointments', 'doctors', ['doctorId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
