"""change the name of doctorAvailability fields

Revision ID: 52e3fe4c227a
Revises: 516cd866c765
Create Date: 2025-08-15 15:23:05.156367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52e3fe4c227a'
down_revision: Union[str, Sequence[str], None] = '516cd866c765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_patientId_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_doctorId_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'patients', ['patientId'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctorId'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('doctor_availability', sa.Column('startTime', sa.Time(), nullable=True))
    op.add_column('doctor_availability', sa.Column('endTime', sa.Time(), nullable=True))
    op.drop_constraint(op.f('doctor_availability_doctorId_fkey'), 'doctor_availability', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_availability', 'doctors', ['doctorId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('doctor_availability', 'availableFrom')
    op.drop_column('doctor_availability', 'availableTo')
    op.drop_constraint(op.f('doctor_treatment_junction_doctorId_fkey'), 'doctor_treatment_junction', type_='foreignkey')
    op.drop_constraint(op.f('doctor_treatment_junction_treatmentId_fkey'), 'doctor_treatment_junction', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_treatment_junction', 'treatments', ['treatmentId'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'doctor_treatment_junction', 'doctors', ['doctorId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('health_reports_doctor_id_fkey'), 'health_reports', type_='foreignkey')
    op.drop_constraint(op.f('health_reports_patient_id_fkey'), 'health_reports', type_='foreignkey')
    op.create_foreign_key(None, 'health_reports', 'patients', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'health_reports', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('medications_patient_id_fkey'), 'medications', type_='foreignkey')
    op.drop_constraint(op.f('medications_doctor_id_fkey'), 'medications', type_='foreignkey')
    op.create_foreign_key(None, 'medications', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'medications', 'patients', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('patient_files_patientId_fkey'), 'patient_files', type_='foreignkey')
    op.create_foreign_key(None, 'patient_files', 'patients', ['patientId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('patient_medical_info_appointmentId_fkey'), 'patient_medical_info', type_='foreignkey')
    op.drop_constraint(op.f('patient_medical_info_patientId_fkey'), 'patient_medical_info', type_='foreignkey')
    op.create_foreign_key(None, 'patient_medical_info', 'patients', ['patientId'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'patient_medical_info', 'appointments', ['appointmentId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('reviews_treatment_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_patient_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_doctor_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'patients', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'reviews', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'reviews', 'treatments', ['treatment_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('surgeries_performed_patient_id_fkey'), 'surgeries_performed', type_='foreignkey')
    op.drop_constraint(op.f('surgeries_performed_doctor_id_fkey'), 'surgeries_performed', type_='foreignkey')
    op.create_foreign_key(None, 'surgeries_performed', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'surgeries_performed', 'patients', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('surgery_schedules_doctor_id_fkey'), 'surgery_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'surgery_schedules', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surgery_schedules', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('surgery_schedules_doctor_id_fkey'), 'surgery_schedules', 'doctors', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'surgeries_performed', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'surgeries_performed', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('surgeries_performed_doctor_id_fkey'), 'surgeries_performed', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key(op.f('surgeries_performed_patient_id_fkey'), 'surgeries_performed', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'reviews', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'reviews', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'reviews', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_doctor_id_fkey'), 'reviews', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key(op.f('reviews_patient_id_fkey'), 'reviews', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('reviews_treatment_id_fkey'), 'reviews', 'treatments', ['treatment_id'], ['id'])
    op.drop_constraint(None, 'patient_medical_info', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'patient_medical_info', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('patient_medical_info_patientId_fkey'), 'patient_medical_info', 'patients', ['patientId'], ['id'])
    op.create_foreign_key(op.f('patient_medical_info_appointmentId_fkey'), 'patient_medical_info', 'appointments', ['appointmentId'], ['id'])
    op.drop_constraint(None, 'patient_files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('patient_files_patientId_fkey'), 'patient_files', 'patients', ['patientId'], ['id'])
    op.drop_constraint(None, 'medications', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'medications', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('medications_doctor_id_fkey'), 'medications', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key(op.f('medications_patient_id_fkey'), 'medications', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'health_reports', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'health_reports', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('health_reports_patient_id_fkey'), 'health_reports', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('health_reports_doctor_id_fkey'), 'health_reports', 'doctors', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'doctor_treatment_junction', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'doctor_treatment_junction', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_treatment_junction_treatmentId_fkey'), 'doctor_treatment_junction', 'treatments', ['treatmentId'], ['id'])
    op.create_foreign_key(op.f('doctor_treatment_junction_doctorId_fkey'), 'doctor_treatment_junction', 'doctors', ['doctorId'], ['id'])
    op.add_column('doctor_availability', sa.Column('availableTo', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('doctor_availability', sa.Column('availableFrom', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'doctor_availability', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_availability_doctorId_fkey'), 'doctor_availability', 'doctors', ['doctorId'], ['id'])
    op.drop_column('doctor_availability', 'endTime')
    op.drop_column('doctor_availability', 'startTime')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_doctorId_fkey'), 'appointments', 'doctors', ['doctorId'], ['id'])
    op.create_foreign_key(op.f('appointments_patientId_fkey'), 'appointments', 'patients', ['patientId'], ['id'])
    # ### end Alembic commands ###
