"""Change the datatypes int the medical Info table

Revision ID: d381a9d2f6aa
Revises: b2376509945c
Create Date: 2025-08-13 13:45:38.336959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd381a9d2f6aa'
down_revision: Union[str, Sequence[str], None] = 'b2376509945c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'patient_medical_info',
        'bodyTempearture',  # old name (typo)
        new_column_name='bodyTemperature',
        existing_type=sa.Integer(),  # old type
        existing_nullable=True
    )
    op.alter_column('patient_medical_info','bodyTemperature',
                existing_type=sa.Integer(),
                type_=sa.String(),
                existing_nullable=True
                    )
    op.alter_column('patient_medical_info','heartRate',
                existing_type=sa.Integer(),
                type_=sa.String(),
                existing_nullable=True
                    )
    op.alter_column('patient_medical_info','respirationRate',
                existing_type=sa.Integer(),
                type_=sa.String(),
                existing_nullable=True
                    )
    op.alter_column('patient_medical_info','bloodPressure',
                existing_type=sa.Integer(),
                type_=sa.String(),
                existing_nullable=True
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 1. Change column types back to Integer
    op.alter_column(
        'patient_medical_info',
        'bodyTemperature',
        existing_type=sa.String(),
        type_=sa.Integer(),
        existing_nullable=True
    )
    op.alter_column(
        'patient_medical_info',
        'heartRate',
        existing_type=sa.String(),
        type_=sa.Integer(),
        existing_nullable=True
    )
    op.alter_column(
        'patient_medical_info',
        'respirationRate',
        existing_type=sa.String(),
        type_=sa.Integer(),
        existing_nullable=True
    )
    op.alter_column(
        'patient_medical_info',
        'bloodPressure',
        existing_type=sa.String(),
        type_=sa.Integer(),
        existing_nullable=True
    )

    # 2. Rename column back to typo'd name
    op.alter_column(
        'patient_medical_info',
        'bodyTemperature',
        new_column_name='bodytempearture',
        existing_type=sa.Integer(),
        existing_nullable=True
    )
