"""create new table of role and permission

Revision ID: e8982ae21188
Revises: 3399fc4c4467
Create Date: 2025-08-20 13:37:57.782916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8982ae21188'
down_revision: Union[str, Sequence[str], None] = '3399fc4c4467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_public_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_constraint(op.f('appointments_treatmentId_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_doctorId_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_patientId_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctorId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'treatments', ['treatmentId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'patients', ['patientId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('doctor_availability_doctorId_fkey'), 'doctor_availability', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_availability', 'doctors', ['doctorId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('doctor_treatment_junction_doctorId_fkey'), 'doctor_treatment_junction', type_='foreignkey')
    op.drop_constraint(op.f('doctor_treatment_junction_treatmentId_fkey'), 'doctor_treatment_junction', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_treatment_junction', 'doctors', ['doctorId'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'doctor_treatment_junction', 'treatments', ['treatmentId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('health_reports_patient_id_fkey'), 'health_reports', type_='foreignkey')
    op.drop_constraint(op.f('health_reports_doctor_id_fkey'), 'health_reports', type_='foreignkey')
    op.create_foreign_key(None, 'health_reports', 'patients', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'health_reports', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('medications_patient_id_fkey'), 'medications', type_='foreignkey')
    op.drop_constraint(op.f('medications_doctor_id_fkey'), 'medications', type_='foreignkey')
    op.create_foreign_key(None, 'medications', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'medications', 'patients', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('patient_files_patientId_fkey'), 'patient_files', type_='foreignkey')
    op.create_foreign_key(None, 'patient_files', 'patients', ['patientId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('patient_medical_info_appointmentId_fkey'), 'patient_medical_info', type_='foreignkey')
    op.drop_constraint(op.f('patient_medical_info_patientId_fkey'), 'patient_medical_info', type_='foreignkey')
    op.create_foreign_key(None, 'patient_medical_info', 'patients', ['patientId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'patient_medical_info', 'appointments', ['appointmentId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('permissions', sa.Column('description', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('reviews_doctor_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_patient_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_treatment_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'patients', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'reviews', 'treatments', ['treatment_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'reviews', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('role_permission_junction_roleId_fkey'), 'role_permission_junction', type_='foreignkey')
    op.drop_constraint(op.f('role_permission_junction_permissionId_fkey'), 'role_permission_junction', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission_junction', 'roles', ['roleId'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'role_permission_junction', 'permissions', ['permissionId'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('roles', sa.Column('createdAt', sa.Date(), nullable=True))
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(op.f('surgeries_performed_doctor_id_fkey'), 'surgeries_performed', type_='foreignkey')
    op.drop_constraint(op.f('surgeries_performed_patient_id_fkey'), 'surgeries_performed', type_='foreignkey')
    op.create_foreign_key(None, 'surgeries_performed', 'patients', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'surgeries_performed', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('surgery_schedules_doctor_id_fkey'), 'surgery_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'surgery_schedules', 'doctors', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('users', sa.Column('roleId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['roleId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.drop_column('users', 'roleId')
    op.drop_constraint(None, 'surgery_schedules', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('surgery_schedules_doctor_id_fkey'), 'surgery_schedules', 'doctors', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'surgeries_performed', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'surgeries_performed', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('surgeries_performed_patient_id_fkey'), 'surgeries_performed', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('surgeries_performed_doctor_id_fkey'), 'surgeries_performed', 'doctors', ['doctor_id'], ['id'])
    op.alter_column('roles', 'description',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('roles', 'createdAt')
    op.drop_constraint(None, 'role_permission_junction', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'role_permission_junction', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('role_permission_junction_permissionId_fkey'), 'role_permission_junction', 'permissions', ['permissionId'], ['id'])
    op.create_foreign_key(op.f('role_permission_junction_roleId_fkey'), 'role_permission_junction', 'roles', ['roleId'], ['id'])
    op.drop_constraint(None, 'reviews', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'reviews', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'reviews', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_treatment_id_fkey'), 'reviews', 'treatments', ['treatment_id'], ['id'])
    op.create_foreign_key(op.f('reviews_patient_id_fkey'), 'reviews', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('reviews_doctor_id_fkey'), 'reviews', 'doctors', ['doctor_id'], ['id'])
    op.drop_column('permissions', 'description')
    op.drop_constraint(None, 'patient_medical_info', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'patient_medical_info', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('patient_medical_info_patientId_fkey'), 'patient_medical_info', 'patients', ['patientId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('patient_medical_info_appointmentId_fkey'), 'patient_medical_info', 'appointments', ['appointmentId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'patient_files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('patient_files_patientId_fkey'), 'patient_files', 'patients', ['patientId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'medications', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'medications', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('medications_doctor_id_fkey'), 'medications', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key(op.f('medications_patient_id_fkey'), 'medications', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'health_reports', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'health_reports', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('health_reports_doctor_id_fkey'), 'health_reports', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key(op.f('health_reports_patient_id_fkey'), 'health_reports', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'doctor_treatment_junction', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'doctor_treatment_junction', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_treatment_junction_treatmentId_fkey'), 'doctor_treatment_junction', 'treatments', ['treatmentId'], ['id'])
    op.create_foreign_key(op.f('doctor_treatment_junction_doctorId_fkey'), 'doctor_treatment_junction', 'doctors', ['doctorId'], ['id'])
    op.drop_constraint(None, 'doctor_availability', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_availability_doctorId_fkey'), 'doctor_availability', 'doctors', ['doctorId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_patientId_fkey'), 'appointments', 'patients', ['patientId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('appointments_doctorId_fkey'), 'appointments', 'doctors', ['doctorId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('appointments_treatmentId_fkey'), 'appointments', 'treatments', ['treatmentId'], ['id'], ondelete='CASCADE')
    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('roleId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['roleId'], ['roles.id'], name=op.f('user_roles_roleId_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('user_roles_userId_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_roles_pkey'))
    )
    op.create_index(op.f('ix_public_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('roleId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['roleId'], ['roles.id'], name=op.f('role_permissions_roleId_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('role_permissions_pkey'))
    )
    op.create_index(op.f('ix_public_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    # ### end Alembic commands ###
