export const patients = [
	{
		id: 'PB-001',
		name: 'Sarah Miller',
		avatar: 'https://randomuser.me/api/portraits/women/1.jpg',
		date: '2028-09-12',
		time: '09:00 AM',
		doctor: 'Dr. Olivia Grant',
		doctorAvatar: 'https://randomuser.me/api/portraits/women/21.jpg',
		treatment: 'Facial Rejuvenation',
		status: 'Completed',
		hpi: 'HPI-001',
		expiryDate: '2032-01-01',
		age: '29 years old',
		gender: 'Female',
		birthday: '1999-04-28',
		about:
			'Sarah is a regular patient undergoing facial rejuvenation treatments to maintain skin health.',
		phone: '+1 555-123-4567',
		address: '123 Main St, Springfield, USA',
		email: 'sarah.miller@example.com',
		emergencyContact: 'John Miller (+1 555-987-6543)',
		allergies: ['Penicillin', 'Pollen', 'Latex'],
		medications: [
			'Ibuprofen (200 mg as needed)',
			'Cetirizine (10 mg daily for allergies)',
			'Vitamin D supplements'
		],
		bodyTemperature: '37',
		heartRate: '72',
		bloodPressure: '120',
		respiratory: '16'
	},
	{
		id: 'PB-002',
		name: 'Maurice Galley',
		avatar: 'https://randomuser.me/api/portraits/men/2.jpg',
		date: '2028-09-12',
		time: '12:00 PM',
		doctor: 'Dr. David Carter',
		doctorAvatar: 'https://randomuser.me/api/portraits/men/22.jpg',
		treatment: 'Laser Hair Removal',
		status: 'In Progress',
		hpi: 'HPI-002',
		expiryDate: '2032-01-01',
		age: '32 years old',
		gender: 'Male',
		birthday: '1992-07-15',
		about: 'Maurice is undergoing a series of laser hair removal sessions.',
		phone: '+1 555-234-5678',
		address: '456 Elm St, Springfield, USA',
		email: 'maurice.galley@example.com',
		emergencyContact: 'Anna Galley (+1 555-654-3210)',
		allergies: ['Pollen', 'Latex'],
		medications: ['Cetirizine (10 mg daily for allergies)', 'Vitamin D supplements'],
		bodyTemperature: '36.9',
		heartRate: '75',
		bloodPressure: '118',
		respiratory: '17'
	},
	{
		id: 'PB-003',
		name: 'Julia Watson',
		avatar: 'https://randomuser.me/api/portraits/women/3.jpg',
		date: '2028-09-12',
		time: '02:30 PM',
		doctor: 'Dr. Emily Ross',
		doctorAvatar: 'https://randomuser.me/api/portraits/women/23.jpg',
		treatment: 'Botox Injections',
		status: 'Scheduled',
		hpi: 'HPI-003',
		expiryDate: '2032-01-01',
		age: '27 years old',
		gender: 'Female',
		birthday: '1997-03-10',
		about: 'Julia has scheduled Botox treatment to reduce fine lines.',
		phone: '+1 555-345-6789',
		address: '789 Oak St, Springfield, USA',
		email: 'julia.watson@example.com',
		emergencyContact: 'Peter Watson (+1 555-765-4321)',
		allergies: ['Penicillin'],
		medications: ['Ibuprofen (200 mg as needed)'],
		bodyTemperature: '37.1',
		heartRate: '70',
		bloodPressure: '119',
		respiratory: '16'
	},
	{
		id: 'PB-004',
		name: 'Stephen Hawk',
		avatar: 'https://randomuser.me/api/portraits/men/4.jpg',
		date: '2028-09-12',
		time: '04:30 PM',
		doctor: 'Dr. James Lawson',
		doctorAvatar: 'https://randomuser.me/api/portraits/men/24.jpg',
		treatment: 'Microdermabrasion',
		status: 'Completed',
		hpi: 'HPI-004',
		expiryDate: '2032-01-01',
		age: '40 years old',
		gender: 'Male',
		birthday: '1984-11-21',
		about: 'Stephen underwent microdermabrasion for skin resurfacing.',
		phone: '+1 555-456-7890',
		address: '321 Pine St, Springfield, USA',
		email: 'stephen.hawk@example.com',
		emergencyContact: 'Laura Hawk (+1 555-321-6547)',
		allergies: ['Latex'],
		medications: ['Vitamin D supplements'],
		bodyTemperature: '37.2',
		heartRate: '74',
		bloodPressure: '121',
		respiratory: '15'
	},
	{
		id: 'PB-005',
		name: 'Emma Wilson',
		avatar: 'https://randomuser.me/api/portraits/women/5.jpg',
		date: '2028-09-13',
		time: '09:30 AM',
		doctor: 'Dr. Sophia Clark',
		doctorAvatar: 'https://randomuser.me/api/portraits/women/25.jpg',
		treatment: 'Chemical Peels',
		status: 'In Progress',
		hpi: 'HPI-005',
		expiryDate: '2032-01-01',
		age: '30 years old',
		gender: 'Female',
		birthday: '1995-06-12',
		about: 'Emma is receiving chemical peel treatments to improve skin texture.',
		phone: '+1 555-567-8901',
		address: '654 Maple St, Springfield, USA',
		email: 'emma.wilson@example.com',
		emergencyContact: 'David Wilson (+1 555-432-7654)',
		allergies: ['Pollen', 'Penicillin'],
		medications: ['Cetirizine (10 mg daily for allergies)', 'Vitamin D supplements'],
		bodyTemperature: '37',
		heartRate: '73',
		bloodPressure: '117',
		respiratory: '16'
	},
	{
		id: 'PB-006',
		name: 'Victor Ramirez',
		avatar: 'https://randomuser.me/api/portraits/men/6.jpg',
		date: '2028-09-13',
		time: '01:00 PM',
		doctor: 'Dr. Richard Allen',
		doctorAvatar: 'https://randomuser.me/api/portraits/men/26.jpg',
		treatment: 'Body Contouring',
		status: 'Scheduled',
		hpi: 'HPI-006',
		expiryDate: '2032-01-01',
		age: '35 years old',
		gender: 'Male',
		birthday: '1989-02-18',
		about: 'Victor is scheduled for body contouring treatment to enhance physique.',
		phone: '+1 555-678-9012',
		address: '987 Cedar St, Springfield, USA',
		email: 'victor.ramirez@example.com',
		emergencyContact: 'Maria Ramirez (+1 555-210-9876)',
		allergies: ['Latex'],
		medications: ['Ibuprofen (200 mg as needed)'],
		bodyTemperature: '37.3',
		heartRate: '76',
		bloodPressure: '122',
		respiratory: '17'
	},
	{
		id: 'PB-007',
		name: 'Grace Parker',
		avatar: 'https://randomuser.me/api/portraits/women/7.jpg',
		date: '2028-09-13',
		time: '04:00 PM',
		doctor: 'Dr. Megan Foster',
		doctorAvatar: 'https://randomuser.me/api/portraits/women/27.jpg',
		treatment: 'Acne Treatment',
		status: 'Completed',
		hpi: 'HPI-007',
		expiryDate: '2032-01-01',
		age: '26 years old',
		gender: 'Female',
		birthday: '1998-09-05',
		about: 'Grace completed an acne treatment plan to improve her skin condition.',
		phone: '+1 555-789-0123',
		address: '222 Birch St, Springfield, USA',
		email: 'grace.parker@example.com',
		emergencyContact: 'Liam Parker (+1 555-654-9870)',
		allergies: ['Penicillin', 'Pollen'],
		medications: ['Cetirizine (10 mg daily for allergies)'],
		bodyTemperature: '36.8',
		heartRate: '71',
		bloodPressure: '116',
		respiratory: '16'
	},
	{
		id: 'PB-008',
		name: 'Michael Brown',
		avatar: 'https://randomuser.me/api/portraits/men/8.jpg',
		date: '2028-09-12',
		time: '12:00 PM',
		doctor: 'Dr. David Carter',
		doctorAvatar: 'https://randomuser.me/api/portraits/men/22.jpg',
		treatment: 'Laser Hair Removal',
		status: 'In Progress',
		hpi: 'HPI-008',
		expiryDate: '2032-01-01',
		age: '31 years old',
		gender: 'Male',
		birthday: '1993-05-22',
		about: 'Michael is undergoing laser hair removal to achieve smoother skin.',
		phone: '+1 555-890-1234',
		address: '333 Willow St, Springfield, USA',
		email: 'michael.brown@example.com',
		emergencyContact: 'Sophia Brown (+1 555-876-5432)',
		allergies: ['Latex'],
		medications: ['Ibuprofen (200 mg as needed)', 'Vitamin D supplements'],
		bodyTemperature: '37.2',
		heartRate: '74',
		bloodPressure: '120',
		respiratory: '15'
	},
	{
		id: 'PB-009',
		name: 'Daniel Evans',
		avatar: 'https://randomuser.me/api/portraits/men/9.jpg',
		date: '2028-09-12',
		time: '04:30 PM',
		doctor: 'Dr. James Lawson',
		doctorAvatar: 'https://randomuser.me/api/portraits/men/24.jpg',
		treatment: 'Microdermabrasion',
		status: 'Completed',
		hpi: 'HPI-009',
		expiryDate: '2032-01-01',
		age: '38 years old',
		gender: 'Male',
		birthday: '1986-08-14',
		about: 'Daniel successfully completed microdermabrasion sessions for skin care.',
		phone: '+1 555-901-2345',
		address: '444 Cherry St, Springfield, USA',
		email: 'daniel.evans@example.com',
		emergencyContact: 'Olivia Evans (+1 555-543-2109)',
		allergies: ['Pollen'],
		medications: ['Cetirizine (10 mg daily for allergies)'],
		bodyTemperature: '37',
		heartRate: '72',
		bloodPressure: '118',
		respiratory: '16'
	},
	{
		id: 'PB-010',
		name: 'Noah Davis',
		avatar: 'https://randomuser.me/api/portraits/men/10.jpg',
		date: '2028-09-13',
		time: '01:00 PM',
		doctor: 'Dr. Richard Allen',
		doctorAvatar: 'https://randomuser.me/api/portraits/men/26.jpg',
		treatment: 'Body Contouring',
		status: 'Scheduled',
		hpi: 'HPI-010',
		expiryDate: '2032-01-01',
		age: '33 years old',
		gender: 'Male',
		birthday: '1991-12-30',
		about: 'Noah has scheduled body contouring to improve body shape.',
		phone: '+1 555-012-3456',
		address: '555 Aspen St, Springfield, USA',
		email: 'noah.davis@example.com',
		emergencyContact: 'Emma Davis (+1 555-109-8765)',
		allergies: ['Penicillin', 'Latex'],
		medications: ['Ibuprofen (200 mg as needed)', 'Vitamin D supplements'],
		bodyTemperature: '37.1',
		heartRate: '73',
		bloodPressure: '119',
		respiratory: '16'
	},
	{
		id: 'PB-001',
		name: 'Sarah Miller',
		avatar: 'https://randomuser.me/api/portraits/women/1.jpg',
		date: '2028-09-12',
		time: '09:00 AM',
		doctor: 'Dr. Olivia Grant',
		doctorAvatar: 'https://randomuser.me/api/portraits/women/21.jpg',
		treatment: 'Facial Rejuvenation',
		status: 'Completed',
		hpi: 'HPI-001',
		expiryDate: '2032-01-01',
		age: '29 years old',
		gender: 'Female',
		birthday: '1999-04-28',
		about:
			'Sarah is a regular patient undergoing facial rejuvenation treatments to maintain skin health.',
		phone: '+1 555-123-4567',
		address: '123 Main St, Springfield, USA',
		email: 'sarah.miller@example.com',
		emergencyContact: 'John Miller (+1 555-987-6543)',
		allergies: ['Penicillin', 'Pollen', 'Latex'],
		medications: [
			'Ibuprofen (200 mg as needed)',
			'Cetirizine (10 mg daily for allergies)',
			'Vitamin D supplements'
		],
		bodyTemperature: '37',
		heartRate: '72',
		bloodPressure: '120',
		respiratory: '16'
	},
	{
		id: 'PB-002',
		name: 'Maurice Galley',
		avatar: 'https://randomuser.me/api/portraits/men/2.jpg',
		date: '2028-09-12',
		time: '12:00 PM',
		doctor: 'Dr. David Carter',
		doctorAvatar: 'https://randomuser.me/api/portraits/men/22.jpg',
		treatment: 'Laser Hair Removal',
		status: 'In Progress',
		hpi: 'HPI-002',
		expiryDate: '2032-01-01',
		age: '32 years old',
		gender: 'Male',
		birthday: '1992-07-15',
		about: 'Maurice is undergoing a series of laser hair removal sessions.',
		phone: '+1 555-234-5678',
		address: '456 Elm St, Springfield, USA',
		email: 'maurice.galley@example.com',
		emergencyContact: 'Anna Galley (+1 555-654-3210)',
		allergies: ['Pollen', 'Latex'],
		medications: ['Cetirizine (10 mg daily for allergies)', 'Vitamin D supplements'],
		bodyTemperature: '36.9',
		heartRate: '75',
		bloodPressure: '118',
		respiratory: '17'
	},
	{
		id: 'PB-003',
		name: 'Julia Watson',
		avatar: 'https://randomuser.me/api/portraits/women/3.jpg',
		date: '2028-09-12',
		time: '02:30 PM',
		doctor: 'Dr. Emily Ross',
		doctorAvatar: 'https://randomuser.me/api/portraits/women/23.jpg',
		treatment: 'Botox Injections',
		status: 'Scheduled',
		hpi: 'HPI-003',
		expiryDate: '2032-01-01',
		age: '27 years old',
		gender: 'Female',
		birthday: '1997-03-10',
		about: 'Julia has scheduled Botox treatment to reduce fine lines.',
		phone: '+1 555-345-6789',
		address: '789 Oak St, Springfield, USA',
		email: 'julia.watson@example.com',
		emergencyContact: 'Peter Watson (+1 555-765-4321)',
		allergies: ['Penicillin'],
		medications: ['Ibuprofen (200 mg as needed)'],
		bodyTemperature: '37.1',
		heartRate: '70',
		bloodPressure: '119',
		respiratory: '16'
	},
	{
		id: 'PB-004',
		name: 'Stephen Hawk',
		avatar: 'https://randomuser.me/api/portraits/men/4.jpg',
		date: '2028-09-12',
		time: '04:30 PM',
		doctor: 'Dr. James Lawson',
		doctorAvatar: 'https://randomuser.me/api/portraits/men/24.jpg',
		treatment: 'Microdermabrasion',
		status: 'Completed',
		hpi: 'HPI-004',
		expiryDate: '2032-01-01',
		age: '40 years old',
		gender: 'Male',
		birthday: '1984-11-21',
		about: 'Stephen underwent microdermabrasion for skin resurfacing.',
		phone: '+1 555-456-7890',
		address: '321 Pine St, Springfield, USA',
		email: 'stephen.hawk@example.com',
		emergencyContact: 'Laura Hawk (+1 555-321-6547)',
		allergies: ['Latex'],
		medications: ['Vitamin D supplements'],
		bodyTemperature: '37.2',
		heartRate: '74',
		bloodPressure: '121',
		respiratory: '15'
	},
	{
		id: 'PB-005',
		name: 'Emma Wilson',
		avatar: 'https://randomuser.me/api/portraits/women/5.jpg',
		date: '2028-09-13',
		time: '09:30 AM',
		doctor: 'Dr. Sophia Clark',
		doctorAvatar: 'https://randomuser.me/api/portraits/women/25.jpg',
		treatment: 'Chemical Peels',
		status: 'In Progress',
		hpi: 'HPI-005',
		expiryDate: '2032-01-01',
		age: '30 years old',
		gender: 'Female',
		birthday: '1995-06-12',
		about: 'Emma is receiving chemical peel treatments to improve skin texture.',
		phone: '+1 555-567-8901',
		address: '654 Maple St, Springfield, USA',
		email: 'emma.wilson@example.com',
		emergencyContact: 'David Wilson (+1 555-432-7654)',
		allergies: ['Pollen', 'Penicillin'],
		medications: ['Cetirizine (10 mg daily for allergies)', 'Vitamin D supplements'],
		bodyTemperature: '37',
		heartRate: '73',
		bloodPressure: '117',
		respiratory: '16'
	},
	{
		id: 'PB-006',
		name: 'Victor Ramirez',
		avatar: 'https://randomuser.me/api/portraits/men/6.jpg',
		date: '2028-09-13',
		time: '01:00 PM',
		doctor: 'Dr. Richard Allen',
		doctorAvatar: 'https://randomuser.me/api/portraits/men/26.jpg',
		treatment: 'Body Contouring',
		status: 'Scheduled',
		hpi: 'HPI-006',
		expiryDate: '2032-01-01',
		age: '35 years old',
		gender: 'Male',
		birthday: '1989-02-18',
		about: 'Victor is scheduled for body contouring treatment to enhance physique.',
		phone: '+1 555-678-9012',
		address: '987 Cedar St, Springfield, USA',
		email: 'victor.ramirez@example.com',
		emergencyContact: 'Maria Ramirez (+1 555-210-9876)',
		allergies: ['Latex'],
		medications: ['Ibuprofen (200 mg as needed)'],
		bodyTemperature: '37.3',
		heartRate: '76',
		bloodPressure: '122',
		respiratory: '17'
	},
	{
		id: 'PB-007',
		name: 'Grace Parker',
		avatar: 'https://randomuser.me/api/portraits/women/7.jpg',
		date: '2028-09-13',
		time: '04:00 PM',
		doctor: 'Dr. Megan Foster',
		doctorAvatar: 'https://randomuser.me/api/portraits/women/27.jpg',
		treatment: 'Acne Treatment',
		status: 'Completed',
		hpi: 'HPI-007',
		expiryDate: '2032-01-01',
		age: '26 years old',
		gender: 'Female',
		birthday: '1998-09-05',
		about: 'Grace completed an acne treatment plan to improve her skin condition.',
		phone: '+1 555-789-0123',
		address: '222 Birch St, Springfield, USA',
		email: 'grace.parker@example.com',
		emergencyContact: 'Liam Parker (+1 555-654-9870)',
		allergies: ['Penicillin', 'Pollen'],
		medications: ['Cetirizine (10 mg daily for allergies)'],
		bodyTemperature: '36.8',
		heartRate: '71',
		bloodPressure: '116',
		respiratory: '16'
	},
	{
		id: 'PB-008',
		name: 'Michael Brown',
		avatar: 'https://randomuser.me/api/portraits/men/8.jpg',
		date: '2028-09-12',
		time: '12:00 PM',
		doctor: 'Dr. David Carter',
		doctorAvatar: 'https://randomuser.me/api/portraits/men/22.jpg',
		treatment: 'Laser Hair Removal',
		status: 'In Progress',
		hpi: 'HPI-008',
		expiryDate: '2032-01-01',
		age: '31 years old',
		gender: 'Male',
		birthday: '1993-05-22',
		about: 'Michael is undergoing laser hair removal to achieve smoother skin.',
		phone: '+1 555-890-1234',
		address: '333 Willow St, Springfield, USA',
		email: 'michael.brown@example.com',
		emergencyContact: 'Sophia Brown (+1 555-876-5432)',
		allergies: ['Latex'],
		medications: ['Ibuprofen (200 mg as needed)', 'Vitamin D supplements'],
		bodyTemperature: '37.2',
		heartRate: '74',
		bloodPressure: '120',
		respiratory: '15'
	}
];
